name: manual-trigger
run-name: This should be triggered manually for API

on: workflow_dispatch

jobs:
  echo_success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./
          fetch-depth: 0
          ref: main-sync
      - run: git log --pretty=oneline --graph --decorate --all
      - run: git log origin/main0
      - run: git cherry-pick origin/main0
      # dcommit would occur here
      - run: git push
      - run: git checkout main
      - run: git pull origin main
      - run: git merge main0
      - run: git push origin main
