name: manual-trigger
run-name: This should be triggered manually for API

on: workflow_dispatch

jobs:
  echo_success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./
      - run: git fetch --all
      - run: git checkout main-sync
      - run: git fetch --all
      - run: git log
      - run: git cherry-pick main0
      # dcommit would occur here
      - run: git push
      - run: git checkout main
      - run: git pull origin main
      - run: git merge main0
      - run: git push origin main
