name: on-pr-close
run-name: This workflow will run when a PR is closed

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
    - upside-down

jobs:
  echo_success:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged
    steps:
      - run: exit 1
