name: debug
run-name: Debugging github action things
on:
  workflow_dispatch:
  pull_request:
    types: [opened]
  pull_request_review:
    types: [submitted]

jobs:
  printing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event }}"
