name: update-base-branch
run-name: Update base branch to upside-down

on:
  pull_request:

jobs:
  update-branch:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_PVT_KEY }}
      - name: Update pull request base branch
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/fvelasquezr/fvelasquez-app/pulls/$PR_NUMBER \
          -d '{ "base":"upside-down" }'
